//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recognizer.Dlib.Wrapper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Recognizer.Dlib.Wrapper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dnn_age_predictor_v1.dat.
        /// </summary>
        internal static string age_predictor {
            get {
                return ResourceManager.GetString("age_predictor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dlib_face_recognition_resnet_model_v1 {
            get {
                object obj = ResourceManager.GetObject("dlib_face_recognition_resnet_model_v1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dnn_age_predictor_v1 {
            get {
                object obj = ResourceManager.GetObject("dnn_age_predictor_v1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dnn_gender_classifier_v1 {
            get {
                object obj = ResourceManager.GetObject("dnn_gender_classifier_v1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] mmod_human_face_detector {
            get {
                object obj = ResourceManager.GetObject("mmod_human_face_detector", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dlib_face_recognition_resnet_model_v1.dat.
        /// </summary>
        internal static string ressnet_lossmetrics {
            get {
                return ResourceManager.GetString("ressnet_lossmetrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shape_predictor_5_face_landmarks.dat.
        /// </summary>
        internal static string shape_predictor_5 {
            get {
                return ResourceManager.GetString("shape_predictor_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] shape_predictor_5_face_landmarks {
            get {
                object obj = ResourceManager.GetObject("shape_predictor_5_face_landmarks", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shape_predictor_68_face_landmarks.dat.
        /// </summary>
        internal static string shape_predictor_68 {
            get {
                return ResourceManager.GetString("shape_predictor_68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] shape_predictor_68_face_landmarks {
            get {
                object obj = ResourceManager.GetObject("shape_predictor_68_face_landmarks", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] shape_predictor_68_face_landmarks_GTX {
            get {
                object obj = ResourceManager.GetObject("shape_predictor_68_face_landmarks_GTX", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shape_predictor_68_face_landmarks_GTX.dat.
        /// </summary>
        internal static string shape_predictor_68_gtx {
            get {
                return ResourceManager.GetString("shape_predictor_68_gtx", resourceCulture);
            }
        }
    }
}
